fix: shift headings with commonmark AST
nix-community/nixdoc pull request #115
Opened 2024-03-29 12:07 UTC by hsjobeki

This PR fixes the issue, that the current headings are shifted line wise without taking into the context into account.

Nobody noticed yet i guess. But as we progress with the migration it is rather ugly and should be fixed by now.  

closes #113

Done:

- [x] Bump fix version
- [x] Add/change unit tests

2024-04-02 16:01 UTC, infinisil requested changes

2024-04-02 16:01 UTC, infinisil commented on src/format.rs
> +    comrak::format_commonmark(root, &ComrakOptions::default(), &mut markdown_output).unwrap();
You're not actually using `options` here :sweat_smile: 

Also, you can construct `options` in the beginning and use it for both parsing and rendering.

2024-04-02 16:01 UTC, infinisil commented on src/format.rs
> +    return markdown_output;
```suggestion
    String::from_utf8(markdown_output).unwrap()
```

Also some justification for the `unwrap`'s would be appreciated

2024-04-04 15:03 UTC, hsjobeki commented on src/format.rs
> +    options.render.hardbreaks = true;
Ok we could still introduce this later but maybe. I kind of dislike having double linefeeds for one line break in code files. That increases the filesizes. But i am ok with leaving this out.

2024-04-05 02:34 UTC, infinisil commented
(needs a rebase)

2024-04-09 17:49 UTC, infinisil approved these changes
Looking good to me now, thanks!

2024-04-09 17:49 UTC, merged

2024-04-11 11:30 UTC, infinisil commented
This seems to have broken the Nixpkgs manual build: https://github.com/NixOS/nixpkgs/pull/302990#issuecomment-2049471406