Fix/headings
nix-community/nixdoc pull request #121
Opened 2024-04-25 11:11 UTC by hsjobeki

This PR fixes the problematic that where introduced with using any commonmark parser to shift the headings.

It removes the comrak for markdown parsing.

I figured out that is it sufficient to just format the commonmark ast. The parser has support ALL underlying extensions that we use in nixpkgs docs. Alternatively a parser should preserve whitespace and formatting, but i couldnt find any parser amongst the rust ecosystem with such properties.

The solution now involves to manually track whether we are inside or outside of code-blocks and shift only headings that are not inside a code block and start right at the beginning of the line. 

This should be a pretty solid solution for the problem. 

I also added an additional check to the flake where we build the nixpkgs manual against the current state of nixdoc.

ping @infinisil

2024-04-25 15:00 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2024-04-25-documentation-team-meeting-notes-122/44080/1

2024-05-13 13:18 UTC, hsjobeki commented
@infinisil I know you where busy with some other work. I'd be delighted If you could find time to review this PR or tell me what to do with it.

2024-05-13 17:54 UTC, infinisil requested changes
Overall looking good! Just some minor points

2024-05-13 17:54 UTC, infinisil commented on src/snapshots/nixdoc__test__headings.snap
> +```nix
This looks wrong

2024-05-13 17:54 UTC, infinisil commented on src/format.rs
> +        let fence_line = &trim_leading_whitespace(raw_line, 3);
Where does the 3 come from? A comment would be good :)

2024-05-14 07:18 UTC, hsjobeki commented on src/snapshots/nixdoc__test__headings.snap
> +```nix
This is actually correct.


The expected output is that it should not change the code fences, input is this:


`````md

### h3-heading

```nix
# A comment should not be shifted
```

`````

So the output is correct, comrak crate that i used there before insered whitespace which is also allowed but a little ugly.
This behavior is removed anyways and never made it to the nixpkgs manual. :)

2024-05-16 13:30 UTC, hsjobeki commented on src/format.rs
> +        let fence_line = &trim_leading_whitespace(raw_line, 3);
Added a comment here.

3 whitespaces are okay before code fences according to commonmark. Used this spec. to filter out code fences.

Since for headings the same rule applies, we can also handle indented code blocks easily.

2024-05-17 00:44 UTC, infinisil approved these changes

2024-05-17 00:44 UTC, merged