split out package recipe
nix-community/nixdoc pull request #125
Opened 2024-05-15 21:40 UTC by fricklerhandwerk

this allows for easier re-use in other contexts

2024-05-15 21:55 UTC, infinisil commented on package.nix
> +{ lib, rustPlatform }:
Would you want this file to be a stable interface? If so it should have a comment here (and if not, I don't see a reason for doing this as is)

2024-05-15 22:14 UTC, fricklerhandwerk commented on package.nix
> +{ lib, rustPlatform }:
Hm no, I'd rather have the recipe as an exported attribute in `default.nix`, but that would require tearing apart the whole setup.

2024-05-17 00:11 UTC, fricklerhandwerk commented on package.nix
> +{ lib, rustPlatform }:
Gave it another thought.

2024-05-24 21:08 UTC, infinisil requested changes

2024-05-24 21:08 UTC, infinisil commented on flake.nix
> +      recipes.nixdoc = recipe;
```suggestion
```

Doesn't seem necessary

2024-05-24 21:10 UTC, infinisil commented
This seems fine to me, even if not very standard. If you could add a small changelog entry for this that would be great, since this is essentially a new part of the API.

2024-05-26 11:47 UTC, infinisil approved these changes

2024-05-26 15:06 UTC, merged