feat: add json_output
nix-community/nixdoc pull request #129
Opened 2024-07-31 21:38 UTC by Janik-Haag

This is useful if you have some other tool which makes use of the documentation data, e.g. a function search.

2024-08-07 02:33 UTC, infinisil requested changes
Needs at least a test, but other than that and my comments, this looks good to me :)

2024-08-07 02:33 UTC, infinisil commented on src/main.rs
> +    json_output: bool,
```suggestion
    /// Whether to output JSON
    #[arg(short, long, default_value_t = false)]
    json_output: bool,
```

2024-08-07 02:33 UTC, infinisil commented on src/main.rs
> +        println!("{}", json_string);
This makes it return a JSON list, which might be hard to extend in the future. I'd rather we adhere to [these JSON guidelines](https://github.com/NixOS/nix/blob/master/doc/manual/src/development/json-guideline.md) by returning an object like `{ "functions": [ ... ] }`.

2024-08-26 10:33 UTC, hsjobeki commented
Regarding the whole Format, docbook, etc discussion. I think nixdoc should have a json Output as Default. 
To loosen the coupling between nixdoc and nixpkgs manaul

2024-08-30 20:50 UTC, Janik-Haag commented on src/main.rs
> +        println!("{}", json_string);
I implemented this as I struct:
```rust
struct JsonFormat {
    version: u32,
    entries: Vec<ManualEntry>,
}
```

2024-08-30 21:05 UTC, Janik-Haag commented
> Needs at least a test,

I added a test, and took the opertunity to refactor a bunch of tests, e.g. making the test_main function actually test the main function instead of just some copied code.

> Regarding the whole Format, docbook, etc discussion. I think nixdoc should have a json Output as Default.

I think that this should not happen here, but (if at all) in a new major relase since it breaks current behavior.
Do you see this as a blocker for this pr?

2024-08-30 21:38 UTC, infinisil approved these changes
I don't think the default matters at all really, because I don't expect anybody to use this tool directly, it's all through automation. So definitely not blocking imo, this PR looks good as-is to me, thanks!

2024-08-30 21:39 UTC, merged