Correctly support nested identifiers
nix-community/nixdoc pull request #27
Opened 2022-12-09 19:02 UTC by infinisil

Makes definitions like

    /* Some comment */
    foo.bar.baz = 10;

correctly identify "foo.bar.baz" as the item name, instead of just "foo"

2022-12-10 00:14 UTC, fricklerhandwerk commented
@mightyiam maybe you're interested to take a look?

2023-03-23 21:36 UTC, asymmetric requested changes
Clippy nit, otherwise LGTM.

2023-03-23 21:36 UTC, asymmetric commented on src/main.rs
> +fn retrieve_doc_item<'a>(arena: &Arena<'a>, node: &ASTNode) -> Option<DocItem> {
According to clippy these lifetimes can be elided.

```suggestion
fn retrieve_doc_item(arena: &Arena, node: &ASTNode) -> Option<DocItem> {
```

2023-03-23 21:45 UTC, infinisil commented on src/main.rs
> +fn retrieve_doc_item<'a>(arena: &Arena<'a>, node: &ASTNode) -> Option<DocItem> {
Thanks, updated!

2023-03-24 10:58 UTC, merged