init support for doc-comments
nix-community/nixdoc pull request #91
Opened 2023-11-13 16:31 UTC by hsjobeki

@infinisil 

Adds support for doc-comments.

- [x] support for doc-comments in parallel.
- [ ] Shift all markdown headings down one level, so the nixpkgs manual rendering still works.

2023-11-16 00:35 UTC, infinisil commented
Nice! We should definitely wait for the RFC to be accepted, which should be pretty soon. After that I'm generally in favor of merging it, but we definitely need tests and documentation for this.

2024-01-04 16:23 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2024-01-04-documentation-team-meeting-notes-102/37754/1

2024-02-14 05:15 UTC, hsjobeki commented
@infinisil could i ask you for some review & suggestions?

2024-02-15 16:22 UTC, infinisil requested changes
Overall looking really good!

I'd like to see some extra tests:
- One to make sure that the headings get indented properly
- One to make sure omitting a doc comment from an attribute doesn't duplicate the previous one:

  ```nix
  {
    /** Comment */
    foo = 0;

    # This should not have any docs
    bar = 1;
  }
  ```

2024-02-15 16:22 UTC, infinisil commented on src/comment.rs
> +/// bar: bar;
I guess this is used for the top-level docs comment for files?

2024-02-15 16:22 UTC, infinisil commented on src/format.rs
> +/// Markdown has 6 levels of headings. Everything beyond that (e.g., H7) may produce unexpected renderings.
```suggestion
/// Commonmark markdown has 6 levels of headings. Everything beyond that (e.g., H7) is not supported and may produce unexpected renderings.
```

2024-02-15 16:22 UTC, infinisil commented on src/format.rs
> +    }
Minor suggestion: Would be nice to use [`split_inclusive("\n")`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.split_inclusive) to avoid the second `format!`

2024-02-15 16:22 UTC, infinisil commented on src/format.rs
> +            }
This seems a bit odd, the `handle_indentation` should dedent all lines so that you should be able to assume that any `#` are in the beginning.

2024-02-15 16:22 UTC, infinisil commented on src/format.rs
> +/// Performs a line-wise matching to ' # Heading '
```suggestion
/// Performs a line-wise matching to '# Heading'
```

2024-02-15 16:22 UTC, infinisil commented on src/main.rs
> +    // If there is a doc comment according to RFC145 just return it.
This doesn't seem to be the function handling the legacy path, instead it's `retrieve_doc_item`.

2024-02-15 16:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2024-02-15-documentation-team-meeting-notes-109/39826/1

2024-02-19 10:25 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-54/39990/1

2024-02-24 07:00 UTC, hsjobeki commented on doc/migration.md
> +  - **x**: The value to be returned.
Hm. Yes i know. I tried to not introduce examples that require additional plugins. But i guess its better to embrace consistency.

2024-02-24 07:07 UTC, hsjobeki commented on src/format.rs
> +    }
I decided for `.lines()` because it offers a more agnostic line splitting. e.g in case somebody uses other EOL. (CR LF, LF, and CR).

2024-02-24 08:07 UTC, hsjobeki commented
@infinisil. Just worked your feedback in.

2024-02-24 08:12 UTC, hsjobeki commented on src/comment.rs
> +/// bar: bar;
Yes. Could be used within more nested expressions as well. But overall nixdoc doesn't really support that yet.

2024-02-24 15:06 UTC, mightyiam commented on src/format.rs
> +    }
Just a tiny piece: It's typically either CRLF or LF.

2024-02-25 07:30 UTC, hsjobeki commented on test.nix
Whoops that wasnt suposed to be commited anyways

2024-02-25 12:41 UTC, hsjobeki commented on src/format.rs
> +    }
Ok. i applied the suggested change. I both is fine.

2024-02-25 13:00 UTC, hsjobeki commented
@infinisil to keep you updated. 
I just bootstrapped a cli tool https://github.com/hsjobeki/flutsch. Which in combination with a static analysis tool could replace nixdoc entirely. 

Features such as #98 make more sense on nix value level. Unfortunately the comments are not part of the c++nix ast which requires invoking an addtional (e.g. rnix based) tool.

2024-02-26 14:47 UTC, infinisil reviewed
Just some minor bits now

>  I just bootstrapped a cli tool https://github.com/hsjobeki/flutsch. Which in combination with a static analysis tool could replace nixdoc entirely.

Nice! I generally don't mind archiving nixdoc if there's something better. Though I definitely can't say I'm a fan of C++ :sweat_smile:

2024-02-26 14:47 UTC, infinisil commented on src/format.rs
> +            // }
```suggestion
    let mut hashes = String::new();
    let mut rest = String::new();
    for char in chars {
        match char {
```

2024-02-26 14:47 UTC, infinisil commented on test/headings.md
> +This should be h6
```suggestion
#### h4-heading

Should be h6

##### h5-heading

This should be h6

###### h6-heading

This should be h6
```

2024-02-27 18:29 UTC, merged