feat: support custom prefixes
nix-community/nixdoc pull request #97
Opened 2023-12-07 11:14 UTC by Janik-Haag

This adds the ability to define a custom prefix like `lib` or  `utils` which is currently hardcoded.
~~Sadly this will be probably be a breaking change since I didn't see a way to set default values for arguments~~
The only thing missing from this PR I can think of would be a CHANGELOG.md entry.

2023-12-07 11:15 UTC, Janik-Haag commented
cc @infinisil

2023-12-08 00:51 UTC, infinisil requested changes

2023-12-08 00:51 UTC, infinisil commented on src/main.rs
> +    prefix: String,
Check out `default_value_t` in https://docs.rs/clap/latest/clap/_derive/index.html :)

2023-12-08 11:30 UTC, Janik-Haag commented on src/main.rs
> +    prefix: String,
Thanks, added it, works as expected.

2023-12-10 23:54 UTC, infinisil commented
Looking good!

> The only thing missing from this PR I can think of would be a CHANGELOG.md entry.

That's one thing I'd also like to have, ideally as descriptive as possible :D

2023-12-13 18:54 UTC, infinisil approved these changes
I pushed to update the change log a bit, looking good now!

2023-12-13 18:58 UTC, merged